In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [5]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.svm import SVC
model = SVC(probability=True)

In [ ]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [10]:
from sklearn.model_selection import GridSearchCV

param_grid = {'kernel':['linear','rbf','poly','sigmoid'],
             'gamma':['auto','scale'],
             'C':[10,100,1000,2000,3000]} 

grid = GridSearchCV(model, param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

GridSearchCV(estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [11]:
# print best parameter after tuning 
print(grid.best_params_) 

#CV results
re=grid.cv_results_
print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}
{'mean_fit_time': array([0.05762968, 0.05202866, 0.05734119, 0.03754349, 0.05573411,
       0.04737034, 0.05291343, 0.03919435, 0.18281574, 0.06145229,
       0.18096461, 0.03747454, 0.16327958, 0.06022253, 0.2045342 ,
       0.03589416, 0.84496403, 0.14265332, 1.35493374, 0.03373995,
       0.95353045, 0.15342264, 1.35956345, 0.03418798, 1.66217961,
       0.21268778, 2.51400132, 0.0344667 , 1.72924242, 0.20783606,
       2.25623746, 0.03331013, 2.21839466, 0.26360192, 3.40668645,
       0.03789115, 2.64695091, 0.27349191, 2.855619  , 0.03511438]), 'std_fit_time': array([0.00742042, 0.00478838, 0.00814728, 0.00146411, 0.00420963,
       0.00482072, 0.00561218, 0.00424686, 0.05663233, 0.00615513,
       0.0331288 , 0.00441535, 0.03474798, 0.00807782, 0.08156326,
       0.00441278, 0.17203446, 0.03211923, 0.25790515, 0.00157333,
       0.23870856, 0.02128229, 0.50099258, 0.00154952, 0.42888384,
       0.02383355, 1.19806981, 0.0045995 , 0.51983063, 0.0359402 ,
       0.49433635, 0.00289271, 0.17321578, 0.04434588, 0.47202288,
       0.00187001, 0.72440161, 0.02700513, 0.86431514, 0.00238179]), 'mean_score_time': array([0.03023448, 0.03387251, 0.02913556, 0.03152924, 0.03164768,
       0.03232689, 0.03019657, 0.02846336, 0.02616234, 0.0283917 ,
       0.02316809, 0.02959867, 0.02177262, 0.02448058, 0.02242284,
       0.02318754, 0.02092748, 0.02148838, 0.01979008, 0.02149301,
       0.02087212, 0.0216969 , 0.02120075, 0.0213491 , 0.02021432,
       0.02088609, 0.02106438, 0.02150884, 0.02031994, 0.02119951,
       0.02564397, 0.02245426, 0.02487826, 0.02119069, 0.01655488,
       0.02357216, 0.01947036, 0.02266688, 0.01081476, 0.02072992]), 'std_score_time': array([0.00328235, 0.00283219, 0.00119875, 0.00179228, 0.00107151,
       0.00256359, 0.0010625 , 0.00232293, 0.00144239, 0.00094359,
       0.00373571, 0.00319881, 0.00306106, 0.00315625, 0.00230547,
       0.00218943, 0.00195231, 0.00144563, 0.00119581, 0.00175558,
       0.00069935, 0.00097667, 0.0022088 , 0.00247095, 0.0022087 ,
       0.00329559, 0.00056037, 0.00141928, 0.00262284, 0.00244008,
       0.00492962, 0.00335845, 0.00340906, 0.00112416, 0.00452019,
       0.00158861, 0.00457185, 0.00265401, 0.00019743, 0.00236924]), 'param_C': masked_array(data=[10, 10, 10, 10, 10, 10, 10, 10, 100, 100, 100, 100,
                   100, 100, 100, 100, 1000, 1000, 1000, 1000, 1000, 1000,
                   1000, 1000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
                   2000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=999999), 'param_gamma': masked_array(data=['auto', 'auto', 'auto', 'auto', 'scale', 'scale',
                   'scale', 'scale', 'auto', 'auto', 'auto', 'auto',
                   'scale', 'scale', 'scale', 'scale', 'auto', 'auto',
                   'auto', 'auto', 'scale', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'auto', 'scale', 'scale',
                   'scale', 'scale', 'auto', 'auto', 'auto', 'auto',
                   'scale', 'scale', 'scale', 'scale'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_kernel': masked_array(data=['linear', 'rbf', 'poly', 'sigmoid', 'linear', 'rbf',
                   'poly', 'sigmoid', 'linear', 'rbf', 'poly', 'sigmoid',
                   'linear', 'rbf', 'poly', 'sigmoid', 'linear', 'rbf',
                   'poly', 'sigmoid', 'linear', 'rbf', 'poly', 'sigmoid',
                   'linear', 'rbf', 'poly', 'sigmoid', 'linear', 'rbf',
                   'poly', 'sigmoid', 'linear', 'rbf', 'poly', 'sigmoid',
                   'linear', 'rbf', 'poly', 'sigmoid'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'sigmoid'}], 'split0_test_score': array([0.77629048, 0.86747844, 0.79962013, 0.76267713, 0.77629048,
       0.86747844, 0.79962013, 0.76267713, 0.77629048, 0.86747844,
       0.82209189, 0.80892657, 0.77629048, 0.86747844, 0.82209189,
       0.80892657, 0.77629048, 0.82626263, 0.82209189, 0.79175183,
       0.77629048, 0.84714126, 0.82209189, 0.80892657, 0.77629048,
       0.82626263, 0.82209189, 0.79175183, 0.77629048, 0.82626263,
       0.82209189, 0.80892657, 0.77629048, 0.82626263, 0.82209189,
       0.79175183, 0.77629048, 0.82626263, 0.82209189, 0.80892657]), 'split1_test_score': array([0.79094947, 0.88679245, 0.80839191, 0.73891582, 0.79094947,
       0.88679245, 0.80839191, 0.73891582, 0.79094947, 0.88679245,
       0.78728354, 0.7149311 , 0.79094947, 0.88679245, 0.78728354,
       0.7149311 , 0.79094947, 0.86696784, 0.76555329, 0.7149311 ,
       0.79094947, 0.86696784, 0.76555329, 0.7149311 , 0.79094947,
       0.86696784, 0.76555329, 0.7149311 , 0.79094947, 0.86696784,
       0.76555329, 0.7149311 , 0.79094947, 0.86696784, 0.76555329,
       0.7149311 , 0.79094947, 0.86696784, 0.76555329, 0.7149311 ]), 'split2_test_score': array([0.69823494, 0.86970866, 0.78794275, 0.65579515, 0.69823494,
       0.86970866, 0.78794275, 0.75317976, 0.69823494, 0.87036224,
       0.76655568, 0.6337193 , 0.69823494, 0.87036224, 0.76655568,
       0.69811321, 0.69823494, 0.8515274 , 0.76655568, 0.69811321,
       0.69823494, 0.8515274 , 0.76655568, 0.69811321, 0.69823494,
       0.8515274 , 0.76655568, 0.69811321, 0.69823494, 0.8515274 ,
       0.76655568, 0.69811321, 0.69823494, 0.8515274 , 0.76655568,
       0.69811321, 0.69823494, 0.8515274 , 0.76655568, 0.69811321]), 'split3_test_score': array([0.92351003, 0.94416086, 0.9245283 , 0.79628353, 0.92351003,
       0.94416086, 0.9245283 , 0.77806673, 0.92351003, 0.94416086,
       0.9245283 , 0.7184975 , 0.92351003, 0.94416086, 0.9245283 ,
       0.79628353, 0.92351003, 0.92527158, 0.9245283 , 0.79628353,
       0.92351003, 0.92527158, 0.9245283 , 0.79628353, 0.92351003,
       0.88679245, 0.9245283 , 0.79628353, 0.92351003, 0.88679245,
       0.9245283 , 0.79628353, 0.92351003, 0.84702007, 0.9245283 ,
       0.79628353, 0.92351003, 0.84702007, 0.9245283 , 0.79628353]), 'split4_test_score': array([0.90174425, 0.94304148, 0.90174425, 0.76655568, 0.90174425,
       0.94304148, 0.90174425, 0.76655568, 0.90174425, 0.94304148,
       0.90174425, 0.76655568, 0.90174425, 0.94304148, 0.90174425,
       0.76655568, 0.90174425, 0.92351003, 0.90174425, 0.76655568,
       0.90174425, 0.92351003, 0.90174425, 0.76655568, 0.90174425,
       0.90361034, 0.90174425, 0.76655568, 0.90174425, 0.90361034,
       0.90174425, 0.76655568, 0.90174425, 0.88327784, 0.90174425,
       0.76655568, 0.90174425, 0.88327784, 0.90174425, 0.76655568]), 'mean_test_score': array([0.81814583, 0.90223638, 0.84444547, 0.74404546, 0.81814583,
       0.90223638, 0.84444547, 0.75987902, 0.81814583, 0.90236709,
       0.84044073, 0.72852603, 0.81814583, 0.90236709, 0.84044073,
       0.75696202, 0.81814583, 0.8787079 , 0.83609468, 0.75352707,
       0.81814583, 0.88288362, 0.83609468, 0.75696202, 0.81814583,
       0.86703213, 0.83609468, 0.75352707, 0.81814583, 0.86703213,
       0.83609468, 0.75696202, 0.81814583, 0.85501116, 0.83609468,
       0.75352707, 0.81814583, 0.85501116, 0.83609468, 0.75696202]), 'std_test_score': array([0.08361871, 0.0344308 , 0.05691772, 0.04774326, 0.08361871,
       0.0344308 , 0.05691772, 0.01317221, 0.08361871, 0.03430808,
       0.0623702 , 0.05862459, 0.08361871, 0.03430808, 0.0623702 ,
       0.04374543, 0.08361871, 0.03950322, 0.06654053, 0.04004831,
       0.08361871, 0.03452908, 0.06654053, 0.04374543, 0.08361871,
       0.02694806, 0.06654053, 0.04004831, 0.08361871, 0.02694806,
       0.06654053, 0.04374543, 0.08361871, 0.01920646, 0.06654053,
       0.04004831, 0.08361871, 0.01920646, 0.06654053, 0.04374543]), 'rank_test_score': array([21,  3, 11, 39, 21,  3, 11, 31, 21,  1, 13, 40, 21,  1, 13, 32, 21,
        6, 15, 36, 21,  5, 15, 32, 21,  7, 15, 36, 21,  7, 15, 32, 21,  9,
       15, 36, 21,  9, 15, 32], dtype=int32)}

In [12]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}: 0.9100355779243318

In [13]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[80  5]
 [ 7 42]]

In [14]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.92      0.94      0.93        85
           1       0.89      0.86      0.88        49

    accuracy                           0.91       134
   macro avg       0.91      0.90      0.90       134
weighted avg       0.91      0.91      0.91       134

In [15]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9539015606242497

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.057630,0.007420,0.030234,0.003282,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
1,0.052029,0.004788,0.033873,0.002832,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.867478,0.886792,0.869709,0.944161,0.943041,0.902236,0.034431,3
2,0.057341,0.008147,0.029136,0.001199,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.799620,0.808392,0.787943,0.924528,0.901744,0.844445,0.056918,11
3,0.037543,0.001464,0.031529,0.001792,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.762677,0.738916,0.655795,0.796284,0.766556,0.744045,0.047743,39
4,0.055734,0.004210,0.031648,0.001072,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
5,0.047370,0.004821,0.032327,0.002564,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.867478,0.886792,0.869709,0.944161,0.943041,0.902236,0.034431,3
6,0.052913,0.005612,0.030197,0.001062,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.799620,0.808392,0.787943,0.924528,0.901744,0.844445,0.056918,11
7,0.039194,0.004247,0.028463,0.002323,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.762677,0.738916,0.753180,0.778067,0.766556,0.759879,0.013172,31
8,0.182816,0.056632,0.026162,0.001442,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
9,0.061452,0.006155,0.028392,0.000944,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.867478,0.886792,0.870362,0.944161,0.943041,0.902367,0.034308,1
10,0.180965,0.033129,0.023168,0.003736,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.787284,0.766556,0.924528,0.901744,0.840441,0.062370,13
11,0.037475,0.004415,0.029599,0.003199,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.808927,0.714931,0.633719,0.718497,0.766556,0.728526,0.058625,40
12,0.163280,0.034748,0.021773,0.003061,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
13,0.060223,0.008078,0.024481,0.003156,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.867478,0.886792,0.870362,0.944161,0.943041,0.902367,0.034308,1
14,0.204534,0.081563,0.022423,0.002305,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.787284,0.766556,0.924528,0.901744,0.840441,0.062370,13
15,0.035894,0.004413,0.023188,0.002189,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
16,0.844964,0.172034,0.020927,0.001952,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
17,0.142653,0.032119,0.021488,0.001446,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.925272,0.923510,0.878708,0.039503,6
18,1.354934,0.257905,0.019790,0.001196,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
19,0.033740,0.001573,0.021493,0.001756,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.791752,0.714931,0.698113,0.796284,0.766556,0.753527,0.040048,36
20,0.953530,0.238709,0.020872,0.000699,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
21,0.153423,0.021282,0.021697,0.000977,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.847141,0.866968,0.851527,0.925272,0.923510,0.882884,0.034529,5
22,1.359563,0.500993,0.021201,0.002209,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
23,0.034188,0.001550,0.021349,0.002471,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
24,1.662180,0.428884,0.020214,0.002209,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
25,0.212688,0.023834,0.020886,0.003296,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.886792,0.903610,0.867032,0.026948,7
26,2.514001,1.198070,0.021064,0.000560,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
27,0.034467,0.004600,0.021509,0.001419,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.791752,0.714931,0.698113,0.796284,0.766556,0.753527,0.040048,36
28,1.729242,0.519831,0.020320,0.002623,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
29,0.207836,0.035940,0.021200,0.002440,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.886792,0.903610,0.867032,0.026948,7
30,2.256237,0.494336,0.025644,0.004930,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
31,0.033310,0.002893,0.022454,0.003358,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
32,2.218395,0.173216,0.024878,0.003409,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
33,0.263602,0.044346,0.021191,0.001124,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.847020,0.883278,0.855011,0.019206,9
34,3.406686,0.472023,0.016555,0.004520,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
35,0.037891,0.001870,0.023572,0.001589,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.791752,0.714931,0.698113,0.796284,0.766556,0.753527,0.040048,36
36,2.646951,0.724402,0.019470,0.004572,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
37,0.273492,0.027005,0.022667,0.002654,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.847020,0.883278,0.855011,0.019206,9
38,2.855619,0.864315,0.010815,0.000197,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
39,0.035114,0.002382,0.020730,0.002369,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32

In [18]:
age_input = float(input("Age: "))
salary_input = float(input("Estimated Salary: "))
gender_input = int(input("Gender Male 0 or 1: "))

Age:  25
Estimated Salary:  500000
Gender Male 0 or 1:  0

In [19]:
Future_Prediction = grid.predict([[age_input, salary_input,gender_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]